# version: '3'

# services:
#   app:
#     image: triple3a/gosurvey:v1
#     build: .
#     ports:
#       - "80:80"
#     depends_on:
#       - db
#     environment:
#       SERVER_PORT: 8080
#       MONGO_URI: mongodb://db:27017

#   db:
#     image: mongo:latest
#     restart: always
#     ports:
#       - "27017:27017"